name: Continuous Deployment
on: [push]

jobs:
  docker:
    name: Docker Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Setu Up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mdrahano12/app-golang:1.5
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop backend-golang
          docker container rm backend-golang
          docker pull mdrahano12/app-golang:1.5
          docker run -dp 80:8000 --name backend-golang --detach mdrahano12/app-golang:1.5